spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clientmsdb?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ""
  jpa:
    hibernate:
      ddl-auto: create-drop   # Cria as tabelas no início e remove ao final
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true            # Exibe SQL no console (útil para debug)
  h2:
    console:
      enabled: true           # Ativa console do H2 em /h2-console
      path: /h2-console

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
